language: csharp
dist: trusty
mono: none
dotnet: 2.2.104
install:
- dotnet restore
script:
- dotnet clean src/ds.algorithms.csharp.sln
- dotnet build src/ds.algorithms.csharp.sln
- dotnet test src/ds.algorithms.csharp.tests